server:
  port: 8888

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: "jdbc:postgresql://localhost:5432/khantech-assignment"
    username: khantech
    password: khantech

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: false
    path: /docs
    tags-sorter: alpha
  show-actuator: false

app:
  wallet:
    transaction:
      threshold: 5000
      approval-timeout: 1d
  scheduler:
    enabled: true
    approval-timeout-job:
      # Runs at midnight every day. Use "*/5 * * * * *" for test
      cron: "0 0 0 * * *"
      batch-size: 1000