server:
  port: 8888

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: "jdbc:postgresql://localhost:5432/khantech-assignment"
    username: khantech
    password: khantech